### ISSUE TITLE
NES HDMI + USB-C PD ?

### ISSUE THREAD

**Issue by Moss720** [ShawMerlin/NES-Power-Module-Redesign#20]
hi,

i am wondering, if you are considering doing a USB-C PD + HDMI power module for the NES ?

**Comment by ShawMerlin** [comment]
Currently with the NESRGB mod, it only outputs the RGB format which is a
different format than HDMI.

There has been past NES HDMI projects from others but they are being
produced anymore and we’re not open sourced.

There is Development going in the NES community on something called
LumaCode.  This takes a Luma video signal and then with external equipment
can output HDMI.

Since our “companion” board has an external video out hookup, you would
only simple having the move it on the RGBNES Mod from Composite to Luma and
then utilize an external device to

It’s currently still in development as the proof of concept was created on
a PAL NES.  So if you live in a country that uses PAL, this is something
you could do now.  If not, it will only be a matter of time before they
have a NTSC version.
